create table BF_110
(
  XZQHBH           VARCHAR(30),
  JJDWBH           VARCHAR(30),
  JJDBH            VARCHAR(30),
  GLJJDBH          VARCHAR(30),
  LHLXBH           VARCHAR(30),
  BJFSBH           VARCHAR(30),
  TFHM             VARCHAR(30),
  JJYBH            VARCHAR(30),
  JJYXM            VARCHAR(30),
  BJSJ             DATETIME,
  JJSJ             DATETIME,
  BJDH             VARCHAR(30),
  BJDHYHXM         VARCHAR(200),
  BJDHYHDZ         VARCHAR(200),
  BJRXM            VARCHAR(30),
  BJRXB            VARCHAR(4),
  LXDH             VARCHAR(50),
  SFDZ             VARCHAR(200),
  BJNR             VARCHAR(2000),
  GXDWBH           VARCHAR(30),
  BJLB             VARCHAR(30),
  BJLX             VARCHAR(30),
  BJXL             VARCHAR(30),
  LDGBH            VARCHAR(30),
  YWWXWZ           int,
  YWBZXL           int,
  YWBKRY           int,
  SFSW             int,
  SFSWYBJ          int,
  ZDDWXZB          double,
  ZDDWYZB          double,
  SDDWXZB          double,
  SDDWYZB          double,
  BCJJNR           VARCHAR(2000),
  RKSJC            DATETIME,
  GXSJ             DATETIME,
  GXRXM            VARCHAR(30),
  FKYQ             VARCHAR(30),
  AJZT             int,
  YWXAJBS          int,
  ZFAJBS           int,
  ZAGJ             VARCHAR(36),
  GXRBH            VARCHAR(30),
  TRANSMITUNIT     VARCHAR(30),
  BKRS             int,
  SSRS             int,
  SWRS             int,
  SFBG             int,
  BGAJBH           VARCHAR(30),
  JJLX             VARCHAR(30),
  DZLX             VARCHAR(30),
  JQJB             VARCHAR(30),
  ZHDJ             VARCHAR(30),
  AFSJ             DATETIME,
  FLAG             int,
  JJTBH            VARCHAR(4),
  JJTIP            VARCHAR(23),
  HZSJ             DATETIME,
  HRSC             int,
  JJSC             int,
  JJLYH            VARCHAR(14),
  ZZDW             VARCHAR(80),
  CANRECORD        int,
  HRSJ             DATETIME,
  S_IDENTITYCARDNO VARCHAR(30),
  S_PHONELOCATION  VARCHAR(100),
  S_MARK           VARCHAR(1000),
  D_MARKTIME       DATETIME,
  BZ               int
);
create table BJLXDMB
(
  BJLXDM VARCHAR(6),
  BJLXMC VARCHAR(40),
  SM     VARCHAR(200),
  ID     int
);
create table CAR_GPS
(
	HH VARCHAR(20),
	CPH VARCHAR(50),
	SD double,
	FX double, 
	GPSTIME DATETIME,
	X double,
	Y double,
	XXLX int
);
